Movie cast
HuzaifaHussnain63/MovieApp pull request #4
Opened 2019-07-08 10:51 UTC by HuzaifaHussnain63

Added the following features:
- Add and remove actors from movie cast
- Add and remove posters and trailer

2019-07-08 10:55 UTC, faisalraza commented on app/assets/stylesheets/movies_details.css
> +  max-height: 500px !important
Add semicolon at the end

2019-07-08 10:55 UTC, faisalraza commented on app/assets/stylesheets/movies_details.css
> +  height: 90px !important
Add semicolon at the end

2019-07-08 10:55 UTC, faisalraza commented on app/assets/stylesheets/movies_details.css
> +{
Move it on above line after adding space

2019-07-08 10:56 UTC, faisalraza commented on app/assets/stylesheets/movies_details.css
> +.movie_card{
Add space before `{`

2019-07-08 10:56 UTC, faisalraza commented on app/assets/stylesheets/movies_details.css
> +
Remove extra space

2019-07-08 10:56 UTC, faisalraza commented on app/assets/stylesheets/movies_details.css
> +.movie_thumbnail{
Add space before `{`

2019-07-08 10:57 UTC, faisalraza commented on app/assets/stylesheets/movies_details.css
> +.movie_poster{
Add space before `{`

2019-07-08 10:58 UTC, faisalraza commented on app/controllers/movies_controller.rb
> +    @actors_not_in_movie =  Actor.all.where.not(id: Movie.find(params[:id]).actors)
Extra space before `Actor`

2019-07-08 11:02 UTC, faisalraza commented on app/controllers/movies_controller.rb
> +    @actors_not_in_movie =  Actor.all.where.not(id: Movie.find(params[:id]).actors)
Is this line working fine as you are passing actors to id in the query.
Also create a before_action `set_movie` and remove above line ie, `@movie = Moview.find..`

2019-07-08 11:02 UTC, faisalraza commented on app/controllers/movies_controller.rb
> +    @movie = Movie.find(params[:id])
Remove this line and use before action

2019-07-08 11:05 UTC, faisalraza commented on app/controllers/movies_controller.rb
> +    @movie = Movie.find(params[:movie_id])
We should update it to use :id instead of :movie_id and also use before_action

2019-07-08 11:05 UTC, faisalraza commented on app/controllers/movies_controller.rb
> +    @movie = Movie.find(params[:id])
Use before action

2019-07-08 11:08 UTC, faisalraza commented on app/helpers/movies_helper.rb
> +  def is_admin_signedin?
Rename to `admin_logged_in?`

2019-07-08 11:08 UTC, faisalraza commented on app/helpers/movies_helper.rb
> +    return false
Just use `user_signed_in? && current_user.admin` in this method

2019-07-08 11:08 UTC, faisalraza commented on app/views/actors/edit.html.erb
> +
Extra line

2019-07-08 11:09 UTC, faisalraza commented on app/views/actors/index.html.erb
> +      <%= link_to fa_icon('edit  2x', class: 'pull-right pt-5'), edit_actor_path(actor)   %>
Extra spaces

2019-07-08 11:09 UTC, faisalraza commented on app/views/devise/registrations/edit.html.erb
> +          <%= f.password_field :password, autocomplete: "new-password", class: 'form-control' %>
Use single quotes to make it symmetrical

2019-07-08 11:10 UTC, faisalraza commented on app/views/devise/registrations/edit.html.erb
> +          <%= f.file_field :avatar, class: 'form-control'  %>
Extra space

2019-07-08 11:10 UTC, faisalraza commented on app/views/devise/registrations/edit.html.erb
> +    <p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete,   class: 'btn btn-primary' %></p>
Extra spaces

2019-07-08 11:10 UTC, faisalraza commented on app/views/home/index.html.erb
> +          <div class='card p-0 border movie_card '>
Extra space

2019-07-08 11:11 UTC, faisalraza commented on app/views/home/index.html.erb
> +                </div>
Indentation  issue

2019-07-08 11:11 UTC, faisalraza commented on app/views/movies/_cast.html.erb
> +      <div class='col pt-5'>
Indentation issue

2019-07-08 11:12 UTC, faisalraza commented on app/views/movies/_movie_gallery.html.erb
> +        <h3 class='pt-3'>Trailer<%= link_to fa_icon('minus-circle', class: 'pull-right pb-5'), remove_trailer_path(@movie.id) if is_admin_signedin? %></h3>
Check indentation

2019-07-09 07:32 UTC, shaffan-chaudhry-s63 commented on Gemfile
> +gem 'font-awesome-rails'
mentioned gem version

2019-07-09 07:33 UTC, shaffan-chaudhry-s63 commented on Gemfile
> +gem 'kaminari'
mentioned gem version

2019-07-09 07:34 UTC, shaffan-chaudhry-s63 commented on app/controllers/actors_controller.rb
> +    if @actor.save
Add new line before if

2019-07-09 07:34 UTC, shaffan-chaudhry-s63 commented on app/controllers/actors_controller.rb
> +    if @actor.destroy()
Add new line before if

2019-07-09 07:34 UTC, shaffan-chaudhry-s63 commented on app/controllers/actors_controller.rb
> +    if @actor.update(actor_params)
Add new line before if

2019-07-09 07:35 UTC, shaffan-chaudhry-s63 commented on app/controllers/actors_controller.rb
> +  def authenticate_admin
Move this method to `ApplicationController`

2019-07-09 07:35 UTC, shaffan-chaudhry-s63 commented on app/controllers/actors_controller.rb
> +    flash[:alert] = "You need to be admin to access this section"
Use single quotes for hard coded strings.

2019-07-09 07:36 UTC, shaffan-chaudhry-s63 commented on app/controllers/application_controller.rb
>    protected
Add new line before protected.

2019-07-09 07:39 UTC, shaffan-chaudhry-s63 commented on app/controllers/movies_controller.rb
>      if @movie.destroy()
use `@movie.destroy`

2019-07-09 07:41 UTC, shaffan-chaudhry-s63 commented on app/controllers/movies_controller.rb
> +    @movies = Movie.order(:title).page params[:page]
Order by release date desc

2019-07-09 07:43 UTC, shaffan-chaudhry-s63 commented on app/controllers/movies_controller.rb
> +    @actor = Actor.find(params[:actor_id])
Move it to `@actor = Actor.find(params[:actor_id])`

2019-07-09 07:45 UTC, shaffan-chaudhry-s63 commented on app/controllers/movies_controller.rb
> +    @movie.actors.delete(@actor)
Check success and failure cases

2019-07-09 07:46 UTC, shaffan-chaudhry-s63 commented on app/controllers/movies_controller.rb
> +    @movie.actors << @actor
Check success and failure cases

2019-07-09 07:46 UTC, shaffan-chaudhry-s63 commented on app/controllers/movies_controller.rb
> +    @actor = Actor.find(params[:actor][:id])
Move it to before_action

2019-07-09 07:47 UTC, shaffan-chaudhry-s63 commented on app/controllers/movies_controller.rb
> +    @actor = Actor.find(params[:actor][:id])
`params[:actor][:id]` should be `params[:actor_id]`

2019-07-09 07:52 UTC, shaffan-chaudhry-s63 commented on app/views/actors/_form.html.erb
> +<%= form_with(model: @actor, local:true, method: request_method) do |form| %>
should be: `local: true`

2019-07-09 07:52 UTC, shaffan-chaudhry-s63 commented on app/views/actors/edit.html.erb
> +    <%= render partial: 'form', locals: {request_method: :patch, submit_button_text: 'Update Actor'} %>
Should be `{ request_method: :patch, submit_button_text: 'Update Actor' }`

2019-07-09 08:03 UTC, shaffan-chaudhry-s63 commented on app/views/movies/new.html.erb
> +    <%= render partial: 'form', locals: {request_method: :post, submit_button_text: 'Add Movie'} %>
Indent hash.

2019-07-09 08:21 UTC, shaffan-chaudhry-s63 requested changes
Please incorporate feedback mentioned in comments.

2019-07-09 13:52 UTC, merged

2019-07-09 13:53 UTC, shaffan-chaudhry-s63 approved these changes
Approved.